import makeEnum from "../utils/makeEnum";

export const wsServer = makeEnum(
  "wsServer",
  "INFO",
  "GAME_START_TIME",
  "SEND_CATEGORIES",
  "CHANGE_CONTROLLER",
  "FINAL_SCORES",
  "END_OF_ROUND",
  "GET_DD_WAGER",
  "DISPLAY_ANSWER",
  "PROMPT_SELECT_CLUE",
  "CLUE_SELECTION_TIMEOUT",
  "INVALID_CLUE_SELECTION",
  "FJ_DISPLAY_CATEGORY",
  "FJ_DISPLAY_CLUE",
  "PLAY_THINK_MUSIC",
  "CONNECTED",
  "CLUES",
  "GAME_STATE_CHANGE",
  "CLUE_STATE_CHANGE",
  "FINAL_JEOPARDY_STATE_CHANGE"
);
export const wsClient = makeEnum("wsClient", "CONNECTED", "CONFIRM_CLUES");
